name: GunGame
version: 1.0
author: Dome_HD
description: 
main: net.playinfinity.GunGame.GuneGame.GunGame
commands: 
  setLoc:
    aliases: [setspawn]
  spectator:
    aliases: [spc]      
  Builder:      
  domeMode:   
  stats:         
  shop:
  setcoins:
  setlevel:
  rang:       
  nick:                      